### ISSUE TITLE
Implement a data seeding process to populate the development database with "fake" data.

### ISSUE THREAD

**Issue by KevinW90** [KevinW90/m-tas#12]
# Description
Only one initial seed for the dev database is needed.

## Tasks

- [ ] Generate schema for Adopters
- [ ] Generate schema for Fosters
- [ ] Generate schema for Rescues
- [x] Generate schema for Transport
- [ ] Generate fake data for Adopters
- [ ] Generate fake data for Fosters
- [ ] Generate fake data for Rescues
- [x] Generate fake data for Transport

**Comment by KevinW90** [comment]
close #12
