### ISSUE TITLE
Simulated Connection to Google API

### ISSUE THREAD

**Issue by KevinW90** [KevinW90/m-tas#14]
# Description

Create a simulation to use Google Docs API. This will enable seamless testing by providing a way to mock any requests (read, write) without using an actual request. We can tailor the simulated connection to throw errors on occasion for graceful handling.

## Solution

Develop a mock api endpoint to tag. This endpoint will simulate some time passing and send back a response.

## Tasks

- [x] Mock API Endpoints: Create endpoints that correspond to each of the Google API services the app will use (Drive, Docs, Sheets)
- [x] Simulate Data: Any data will do for testing
- [x] File class to encapsulate Google service logic
- [x] Error Handling: rate limiting, authentication, update requests, ...
- [x] Documentation: Update documentation to include how to use the mock API endpoints

## Expected Deliverables:

- Mock API endpoints for simulating Google Docs' functionalities.
- Simulation mechanism for reading and writing documents.
- Sample data for testing purposes.
- Integration tests to validate the simulated connection.
- Updated documentation explaining the simulated connection setup and usage.

**Comment by KevinW90** [comment]
313ab42f39e673fd8841128ba27e0f1443c003e6
